FROM golang:1.3-cross

RUN go get github.com/tools/godep
RUN go get github.com/mitchellh/gox

ADD . /go/src/github.com/ehazlett/freight

ADD https://get.docker.com/builds/Linux/x86_64/docker-1.5.0 /usr/local/bin/docker

RUN chmod +x /usr/local/bin/docker
ENV GOPATH $GOPATH:/go/src/github.com/ehazlett/freight/freight/Godeps/_workspace

WORKDIR /go/src/github.com/ehazlett/freight

